apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question
  template:
    metadata: 
      labels: 
        app: question
    spec:
      containers:
        - name: question
          image: us.gcr.io/stoked-champion-306202/question
          env:
            - name: MONGO_URI
              value: 'mongodb://question-mongo-srv:27017/question'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: question-srv
spec:
  selector:
    app: question
  ports:
    - name: question
      protocol: TCP
      port: 3000
      targetPort: 3000